# Generated by Django 5.2.9 on 2025-12-21 04:36

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username_user_alias_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +41 79 123 4567). Must start with + and country code.', max_length=20, validators=[account.validators.validate_phone_number], verbose_name='phone number'),
        ),
    ]
