# Generated by Django 5.2.9 on 2026-02-24 09:08

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_verified_emailverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Required. Enter a valid email address.', max_length=254, unique=True, validators=[account.validators.validate_disposable_email], verbose_name='email address'),
        ),
    ]
