# Generated by Django 6.0.2 on 2026-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('args', models.TextField()),
                ('kwargs', models.TextField()),
                ('exception', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
