# Generated by Django 6.0.2 on 2026-03-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_celerytaskerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
            ],
            options={
                'verbose_name': 'active user',
                'verbose_name_plural': 'active users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='PendingVerificationUser',
            fields=[
            ],
            options={
                'verbose_name': 'pending verification user',
                'verbose_name_plural': 'pending verification users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
    ]
