# Generated by Django 6.0.2 on 2026-05-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('ignorable', 'Ignorable')], default='medium', max_length=20, verbose_name='priority'),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=20, verbose_name='provider')),
                ('provider_uid', models.CharField(help_text='Firebase UID from the decoded ID token.', max_length=255, verbose_name='provider UID')),
                ('email', models.EmailField(blank=True, help_text='Email reported by the provider at the time of linking.', max_length=254, verbose_name='provider email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'db_table': 'account_social_account',
                'indexes': [models.Index(fields=['provider', 'provider_uid'], name='account_social_provider_uid_idx')],
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
