# Generated by Django 6.0.2 on 2026-05-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_usernotification_priority_socialaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='account_soc_provide_d2fe83_idx',
            old_name='account_social_provider_uid_idx',
        ),
    ]
