# Generated by Django 6.0.2 on 2026-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_phone_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('phone', 'Phone')], max_length=20, verbose_name='provider'),
        ),
    ]
