# Generated by Django 6.0.2 on 2026-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_free_plan_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
