# Generated by Django 5.2.9 on 2025-12-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=120)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=50)),
                ('target_name', models.CharField(blank=True, max_length=120)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('target_phone', models.CharField(blank=True, max_length=50)),
                ('target_address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('service_channel', models.CharField(choices=[('email', 'E-mail'), ('letter', 'Letter'), ('call', 'Phone call')], default='email', max_length=20)),
                ('call_minutes', models.PositiveIntegerField(default=0, help_text='Estimated minutes if we call.')),
                ('quoted_price_chf', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.shyrequest')),
            ],
        ),
    ]
