# Generated by Django 5.2.9 on 2025-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('requester', 'Requester'), ('staff', 'Staff'), ('responder', 'Responder')], max_length=20),
        ),
    ]
