# Generated by Django 5.2.9 on 2025-12-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('requester', 'Requester'), ('staff', 'Staff')], max_length=20),
        ),
    ]
