# Generated by Django 4.2.27 on 2026-02-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text='e.g. abusive, illegal, human_trafficking', unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, matching content is blocked (rejected).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Censor category',
                'verbose_name_plural': 'Censor categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='e.g. api, chat, upload', max_length=32)),
                ('categories', models.JSONField(default=list, help_text='List of category slugs that triggered.')),
                ('detected_terms', models.JSONField(default=list, help_text='List of detected term strings.')),
                ('blocked', models.BooleanField(default=True)),
                ('text_preview', models.CharField(blank=True, help_text='First 500 chars of input (redacted).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Censor log',
                'verbose_name_plural': 'Censor logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffensiveTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Word or phrase to detect (case-insensitive).', max_length=255)),
                ('term_type', models.CharField(choices=[('word', 'Word'), ('phrase', 'Phrase')], default='word', max_length=10)),
                ('language_code', models.CharField(blank=True, default='', help_text='ISO 639-1 e.g. en, ar, hi. Empty = any language.', max_length=10)),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, content containing this term is blocked.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='chat.censorcategory')),
            ],
            options={
                'verbose_name': 'Offensive term',
                'verbose_name_plural': 'Offensive terms',
                'ordering': ['category', 'term_type', '-term'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='chat_offens_categor_6774db_idx'), models.Index(fields=['language_code', 'is_active'], name='chat_offens_languag_f29683_idx')],
            },
        ),
    ]
