# Generated by Django 4.2.27 on 2026-02-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_censor_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensorTrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Input text (truncated for storage).')),
                ('is_toxic', models.BooleanField(help_text='True = offensive/toxic, False = safe.')),
                ('source', models.CharField(choices=[('google_api', 'Google API (fallback detected)'), ('our_model', 'Our model detected'), ('manual', 'Manual label')], default='google_api', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Toxicity score from API or model.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Censor training example',
                'verbose_name_plural': 'Censor training examples',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'is_toxic'], name='chat_censor_source_6ac2b9_idx')],
            },
        ),
    ]
