# Generated by Django 4.2.27 on 2026-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_censor_training_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_display_name',
            field=models.CharField(blank=True, help_text='Display name for this message (e.g. alias). If blank, derived from request/profile.', max_length=120),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='requester_alias',
            field=models.CharField(blank=True, help_text='Display name for this request (e.g. in chat). If blank, profile alias or requester_name is used.', max_length=120),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('requester', 'Requester'), ('staff', 'Staff'), ('responder', 'Responder')], max_length=20),
        ),
    ]
