# Generated by Django 4.2.27 on 2026-02-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_add_requester_alias_and_sender_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ai_detected',
            field=models.BooleanField(default=False, help_text='True if deal was detected by AI from conversation.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the deal.'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('request_updates', 'Request updates (new messages)'), ('deal_alerts', 'Deal alerts (AI-detected deals)'), ('daily_digest', 'Daily digest (AI summary)')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='chat.shyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'request', 'subscription_type')},
            },
        ),
    ]
