# Generated by Django 6.0.2 on 2026-03-10 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_subscription_and_deal_ai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shyrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender_6551f2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', 'created_at'], name='chat_messag_author__95f2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_email', '-created_at'], name='chat_notifi_recipie_984c53_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_request', 'is_read', '-created_at'], name='chat_notifi_related_f46905_idx'),
        ),
        migrations.AddIndex(
            model_name='shyrequest',
            index=models.Index(fields=['user', '-created_at'], name='chat_shyreq_user_id_734b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='shyrequest',
            index=models.Index(fields=['requester_email', '-created_at'], name='chat_shyreq_request_69b542_idx'),
        ),
        migrations.AddIndex(
            model_name='shyrequest',
            index=models.Index(fields=['status', '-created_at'], name='chat_shyreq_status_cb3d34_idx'),
        ),
    ]
