# Generated by Django 6.0.2 on 2026-03-14 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_threads_and_links(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    ShyRequest = apps.get_model("chat", "ShyRequest")
    Message = apps.get_model("chat", "Message")
    ChatThread = apps.get_model("chat", "ChatThread")
    Notification = apps.get_model("chat", "Notification")
    Deal = apps.get_model("chat", "Deal")

    def user_for_email(email):
        if not email:
            return None
        return User.objects.filter(email__iexact=email).first()

    for shy_request in ShyRequest.objects.all().iterator():
        requester_user = shy_request.requester_user or shy_request.user or user_for_email(shy_request.requester_email)
        target_user = shy_request.target_user or user_for_email(shy_request.target_email)

        updates = []
        if requester_user and shy_request.requester_user_id != requester_user.id:
            shy_request.requester_user_id = requester_user.id
            updates.append("requester_user")
        if requester_user and shy_request.user_id != requester_user.id:
            shy_request.user_id = requester_user.id
            updates.append("user")
        if target_user and shy_request.target_user_id != target_user.id:
            shy_request.target_user_id = target_user.id
            updates.append("target_user")
        if updates:
            shy_request.save(update_fields=updates)

        thread, _ = ChatThread.objects.get_or_create(
            request_id=shy_request.id,
            defaults={
                "requester_user_id": requester_user.id if requester_user else None,
                "requester_email": shy_request.requester_email or "",
                "requester_display_name": shy_request.requester_alias or shy_request.requester_name,
                "target_user_id": target_user.id if target_user else None,
                "target_email": shy_request.target_email or "",
                "target_display_name": shy_request.target_name,
            },
        )

        Message.objects.filter(request_id=shy_request.id, thread__isnull=True).update(thread_id=thread.id)
        Message.objects.filter(request_id=shy_request.id, sender="responder").update(sender="target")
        Message.objects.filter(request_id=shy_request.id, sender="requester").update(
            recipient="target",
            sender_user_id=requester_user.id if requester_user else None,
            recipient_user_id=target_user.id if target_user else None,
            sender_email=shy_request.requester_email or "",
            recipient_email=shy_request.target_email or "",
            recipient_display_name=shy_request.target_name or "",
        )
        Message.objects.filter(request_id=shy_request.id, sender="target").update(
            recipient="requester",
            sender_user_id=target_user.id if target_user else None,
            recipient_user_id=requester_user.id if requester_user else None,
            sender_email=shy_request.target_email or "",
            recipient_email=shy_request.requester_email or "",
            recipient_display_name=shy_request.requester_alias or shy_request.requester_name,
        )
        Message.objects.filter(request_id=shy_request.id, sender="staff").update(
            recipient="requester",
            recipient_user_id=requester_user.id if requester_user else None,
            recipient_email=shy_request.requester_email or "",
            recipient_display_name=shy_request.requester_alias or shy_request.requester_name,
        )

        if shy_request.description and not Message.objects.filter(
            request_id=shy_request.id, message_kind="initial_request"
        ).exists():
            Message.objects.create(
                request_id=shy_request.id,
                thread_id=thread.id,
                sender="requester",
                recipient="target",
                message_kind="initial_request",
                author_id=requester_user.id if requester_user else None,
                sender_user_id=requester_user.id if requester_user else None,
                recipient_user_id=target_user.id if target_user else None,
                sender_email=shy_request.requester_email or "",
                recipient_email=shy_request.target_email or "",
                sender_display_name=shy_request.requester_alias or shy_request.requester_name,
                recipient_display_name=shy_request.target_name or "",
                body=shy_request.description,
                clean_body=shy_request.description,
                is_blocked=False,
            )

    for notification in Notification.objects.filter(recipient_user__isnull=True).iterator():
        recipient_user = user_for_email(notification.recipient_email)
        update_fields = []
        if recipient_user:
            notification.recipient_user_id = recipient_user.id
            update_fields.append("recipient_user")
        if notification.related_request_id and notification.thread_id is None:
            notification.thread_id = ChatThread.objects.get(request_id=notification.related_request_id).id
            update_fields.append("thread")
        if update_fields:
            notification.save(update_fields=update_fields)

    for deal in Deal.objects.all().iterator():
        shy_request = ShyRequest.objects.get(id=deal.request_id)
        thread = ChatThread.objects.get(request_id=deal.request_id)
        update_fields = []
        if deal.thread_id is None:
            deal.thread_id = thread.id
            update_fields.append("thread")
        if deal.requester_user_id is None and shy_request.requester_user_id:
            deal.requester_user_id = shy_request.requester_user_id
            update_fields.append("requester_user")
        if deal.target_user_id is None and shy_request.target_user_id:
            deal.target_user_id = shy_request.target_user_id
            update_fields.append("target_user")
        if update_fields:
            deal.save(update_fields=update_fields)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('chat', '0009_remove_conversation_use_message_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='requester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_kind',
            field=models.CharField(choices=[('initial_request', 'Initial request'), ('reply', 'Reply'), ('note', 'Note')], default='reply', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(choices=[('requester', 'Requester'), ('staff', 'Staff'), ('target', 'Target'), ('system', 'System')], default='target', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='requester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_shy_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_shy_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('requester', 'Requester'), ('staff', 'Staff'), ('target', 'Target'), ('system', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_display_name', models.CharField(blank=True, max_length=120)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('target_display_name', models.CharField(blank=True, max_length=120)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='chat.shyrequest')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_threads', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatthread'),
        ),
        migrations.RunPython(backfill_threads_and_links, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'created_at'], name='chat_messag_recipie_3fc59e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='chat_messag_thread__9895ae_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['requester_email', '-last_message_at'], name='chat_chatth_request_4828a1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['target_email', '-last_message_at'], name='chat_chatth_target__3a1183_idx'),
        ),
    ]
