# Generated by Django 6.0.2 on 2026-03-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_deal_requester_user_deal_target_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatthread',
            name='chat_chatth_request_4828a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatthread',
            name='chat_chatth_target__3a1183_idx',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='thread',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_thread__9895ae_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.DeleteModel(
            name='ChatThread',
        ),
    ]
