# Generated by Django 6.0.2 on 2026-03-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_chatthread_chat_chatth_request_4828a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveShyRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Active request',
                'verbose_name_plural': 'Active requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.shyrequest',),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Conversation message',
                'verbose_name_plural': 'Conversation messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.message',),
        ),
    ]
