# Generated by Django 6.0.3 on 2026-04-14 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_faq_supportticket_supportticketreply_faqvideo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='block_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_shy_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', 'created_at'], name='chat_messag_is_dele_a1a59c_idx'),
        ),
        migrations.AddIndex(
            model_name='shyrequest',
            index=models.Index(fields=['is_deleted', '-created_at'], name='chat_shyreq_is_dele_74f795_idx'),
        ),
        migrations.AddIndex(
            model_name='shyrequest',
            index=models.Index(fields=['is_blocked', '-created_at'], name='chat_shyreq_is_bloc_363299_idx'),
        ),
    ]
