# Generated by Django 6.0.3 on 2026-04-15 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_parent_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deleted_by_sender', 'created_at'], name='chat_messag_deleted_6c9eda_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deleted_by_recipient', 'created_at'], name='chat_messag_deleted_bce7b4_idx'),
        ),
    ]
