# Generated by Django 6.0.3 on 2026-06-16 10:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_participant_read_state(apps, schema_editor):
    ShyRequest = apps.get_model("chat", "ShyRequest")
    Message = apps.get_model("chat", "Message")

    for shy_request in ShyRequest.objects.all().iterator():
        requester_last = (
            Message.objects.filter(
                request_id=shy_request.id,
                recipient="requester",
                is_read=True,
            )
            .order_by("-id")
            .first()
        )
        target_last = (
            Message.objects.filter(
                request_id=shy_request.id,
                recipient="target",
                is_read=True,
            )
            .order_by("-id")
            .first()
        )

        update_fields = []
        if requester_last is not None:
            shy_request.requester_last_read_message_id = requester_last.id
            shy_request.requester_last_read_at = requester_last.read_at or requester_last.created_at
            update_fields.extend(["requester_last_read_message", "requester_last_read_at"])
        if target_last is not None:
            shy_request.target_last_read_message_id = target_last.id
            shy_request.target_last_read_at = target_last.read_at or target_last.created_at
            update_fields.extend(["target_last_read_message", "target_last_read_at"])
        if update_fields:
            shy_request.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_request_status_and_message_read_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='shyrequest',
            name='requester_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='requester_last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='target_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shyrequest',
            name='target_last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.RunPython(backfill_participant_read_state, noop_reverse),
    ]
